### ISSUE TITLE
Customize in-template syntax usage

### ISSUE THREAD

**Issue by yangbo5207** [vue-vine/vue-vine#108]
我比较希望的两个细微调整是
+ 在元素属性中使用括号表示传入的是表达式，而不是 ""
+ 在元素内容中传入表达式使用 单括号，而不是双括号

不知道有没有可能得到支持，当然我知道需要兼容之前的 template 语法这可能会带来一些问题

```diff
return vine`
-  <button @click="increment()">count++</button>
+  <button @click={increment}>count++</button>
-  <div>hello home. {{count}}</div>
+  <div>hello home. {count}</div>
`
```

**Comment by baiwusanyu-c** [comment]
I remember that sfc's parser depends on vue. If so, can we make it an optional compilation configuration? Like this
https://cn.vuejs.org/api/options-rendering.html#compileroptions
@ShenQingchuan

**Comment by ShenQingchuan** [comment]
> I remember that sfc's parser depends on `vue`. If so, can we make it an optional compilation configuration? Like this https://cn.vuejs.org/api/options-rendering.html#compileroptions @ShenQingchuan

是的，理论上是应该可以客制化 `{{ ... }}` 这个行为，但好像也只能做这一个。

任何功能能不能客制化都要看 Vue compiler 本身首先支不支持。

所以我倾向于这个不作为高优先级推进，而且我个人对这个 feature 不持有积极意见。

—————————
Translation:

Yes, theoretically, it should be possible to customize the behavior of `{{ ... }}`, but it seems that's the only thing that can be done.

Whether any feature can be customized depends on whether the Vue compiler itself supports it first.

So, I tend to think that this shouldn't be a high-priority task, and personally, I don't have a positive opinion about this feature.
