### ISSUE TITLE
VSCode extension doesn't recognize props in template

### ISSUE THREAD

**Issue by ShenQingchuan** [vue-vine/vue-vine#111]
### Screenshot

<img width="622" alt="image" src="https://github.com/vue-vine/vue-vine/assets/46062972/5241a2db-fcda-442e-bb04-3ee3f9bed771">

### Description

It seems like that we don't pass in props bindings to Vine language service when user defined props as the formal parameter.

**Comment by cctvhe11** [comment]
感谢大佬

**Comment by ShenQingchuan** [comment]
> 感谢大佬

预计在 **`v0.1.5`** 版本的插件中修复。

**Comment by ShenQingchuan** [comment]
Fixed by https://github.com/vue-vine/vue-vine/releases/tag/v0.1.7
