### ISSUE TITLE
Path resolving behavior align with `index.ts`

### ISSUE THREAD

**Issue by yangbo5207** [vue-vine/vue-vine#115]
我自定义了一个组件，文件结构大概如下
I write a few components, the file structure is roughly as follows

```js
+ NavHeader
    - index.vine.ts
    - othercomp1.vine.ts
    - othercomp2.vine.ts
```

当我在别的页面组件中引入该组件时，我希望使用如下写法可以识别到该组件
When I import this component into another page component, I want it to be recognizable using the following code

```js
import NavHeader from './components/NavHeader'
```

但是现在还不可以，我需要写全 index.vine.ts 的路径
Now this is not working, I need to write a complete path to `index.vine.ts`

```js
import NavHeader from './components/NavHeader/index.vine'
```

不知道未来是否有计划支持这个特性。
Are we going to support a feature like this in the future?

**Comment by so1ve** [comment]
这个是ts的行为，我们管不了

**Comment by so1ve** [comment]
刚刚想了想，如果强行 Patch TypeScript 的代码是可以做的，但是会造成二义性，比如 `index.ts` 和 `index.vine.ts` 同时存在。况且这个解析逻辑不止 TypeScript 使用，bundler 也是这个行为，如果要更改工作量可能会很大。

**Comment by ShenQingchuan** [comment]
Hi，很高兴你能够提出这个意见。
诚实地讲，这个想法非常有建设性，但是如 @so1ve 所说，这的确是一个 TS 的预置行为。
我们暂时无法在外部任何工具链层面参与处理。

我对这个问题有 2 个可能可以实现的思路：

1. 在 Vite 插件处去处理路径解析，至少能够保证运行时层面 “能用”。而 IDE 之中的路径识别这个可能还需要更多研究
2. 推荐你使用 伟大的 AnthonyFu 老师提供的自动导入工具：[unplugin-auto-import](https://github.com/unplugin/unplugin-auto-import)

**Comment by yangbo5207** [comment]
感谢解答  @so1ve @ShenQingchuan
