### ISSUE TITLE
Support hot-key for inserting comment inside vine`...` template

### ISSUE THREAD

**Issue by yangbo5207** [vue-vine/vue-vine#116]
在同一个文件中，同样的快捷键，可以在其他地方注释掉目标代码， `vine` 模板代码中没有任何响应

In the same file, the same shortcut key can comment out the target code in other places, but there is no response in the `vine` template code.

**Comment by ShenQingchuan** [comment]
应已经在 **`v0.1.8`** 版本的 VSCode 插件中修复。

Fixed in VSCode extension in **`v0.1.8`**
