### ISSUE TITLE
Support for export default function MyComponent() {} syntax

### ISSUE THREAD

**Issue by larry-xue** [vue-vine/vue-vine#118]
版本：vue-vine v0.1.9
问题：使用 `export default function MyComponent() {}` 语法时报错：`Uncaught SyntaxError: The requested module '/src/components/Todo.vine.ts?t=1720750152639' does not provide an export named 'default' (at App.vue:2:8)`
复现地址：https://stackblitz.com/edit/vitejs-vite-ao6wgp?file=src%2Fcomponents%2FTodo.vine.ts

---

Version: vue-vine v0.1.9
Issue: Error occurs when using `export default function MyComponent() {}` syntax: `Uncaught SyntaxError: The requested module '/src/components/Todo.vine.ts?t=1720750152639' does not provide an export named 'default' (at App.vue:2:8)`
Reproducible link: https://stackblitz.com/edit/vitejs-vite-ao6wgp?file=src%2Fcomponents%2FTodo.vine.ts

**Comment by ShenQingchuan** [comment]
🥳🎉 Fixed in **`v0.1.10`**

https://stackblitz.com/edit/vitejs-vite-xc5obd?file=src/components/Todo.vine.ts
