### ISSUE TITLE
Not working when define async function as component

### ISSUE THREAD

**Issue by yangbo5207** [vue-vine/vue-vine#120]
我的初衷是想要尝试一下在 vine 中使用 `Suspense`
My original intention was to try using `Suspense` in vine

我的定义方式大概如下。
The way I define it is roughly as follows.

```js
async function Dashboard() {
  const res = await fetch('https://randomuser.me/api/?results=3&inc=name,gender,email,nat,picture&noinfo')
  console.log(res)
  ...
}
```

目前编译之后会直接报错。
Currently, errors are reported directly after compilation.

<img width="951" alt="image" src="https://github.com/user-attachments/assets/4b7d95f8-cf02-4083-a575-fef75d255b3c">

语法提示也会比较乱， await 好像会拦截后续的解析
Syntax prompts are also messy, and await seems to block subsequent parsing.

<img width="646" alt="image" src="https://github.com/user-attachments/assets/644fe5fa-9c30-41b3-8dd2-17a22f0ae3ec">

不知道如何支持类似的用法，还是说有别的方式。
I don't know how to support similar usage, or if there is another way.

**Comment by ShenQingchuan** [comment]
> 目前编译之后会直接报错。
> Currently, errors are reported directly after compilation.

@yangbo5207 在这张截图中目前能看到的只有错误的调用栈 Stack 信息，但能否截一张更完整的图，除了 err.stack 之外，我想确认一下 err.msg 

另外，对于异步组件（即我意指 setup 函数是 async 的情况）
目前 Vine 还没有实际上在初期设计上注意到这一点。我们将高优先级地立刻处理这个问题

———————
Translation:
@yangbo5207 In this screenshot, only the call Stack information can be seen, but can you take a more complete picture? In addition to err.stack, I would like to confirm err.msg

Also, for asynchronous components (i.e. I mean the setup function is async)
Vine hasn't actually paid attention to this in its initial design yet. We will address this issue as a matter of high priority immediately

**Comment by yangbo5207** [comment]
@ShenQingchuan 好像没有别的更有价值的异常信息了

<img width="1237" alt="image" src="https://github.com/user-attachments/assets/e1184016-6ec3-4be8-995e-98c04ed1751a">

<img width="765" alt="image" src="https://github.com/user-attachments/assets/5ea0c870-7aa9-4878-8e41-ff07254e9256">
