### ISSUE TITLE
Can't type check with vue-tsc

### ISSUE THREAD

**Issue by yangbo5207** [vue-vine/vue-vine#123]
<img width="857" alt="image" src="https://github.com/user-attachments/assets/7b8ab037-f09d-4a74-abfa-b56b44e5c858">

报错的主要信息为  `'cls' is declared but its value is never read.`

<img width="644" alt="image" src="https://github.com/user-attachments/assets/6665f6d1-9b07-4461-98b5-1636cfc6242e">

**Comment by ShenQingchuan** [comment]
的确现在 vue-tsc 常在还无法正常识别和检测。我们看一下怎么后续集成和跟进做支持。

Indeed, vue-tsc is often not recognized and detected normally. Let's see how to follow-up integration and follow-up support.

**Comment by ShenQingchuan** [comment]
请使用 [`vue-vine-tsc`](https://www.npmjs.com/package/vue-vine-tsc)

另外现在 vue-vine-tsc 报告的问题是全量、准确的。但在 IDE 中 `.vue` 文件上可能会有部分错误没有显示出来，这个我们在另一个 issue 中后续跟进。


——————
Translation:
Please use [`vue-vine-tsc`](https://www.npmjs.com/package/vue-vine-tsc)

In addition, the problems that vue-vine-tsc reports are now full and accurate. But in VSCode there may be a part of diagnostics in `.vue` file that doesn't show up, which we'll track in another issue.
