### ISSUE TITLE
Not recognize macro types but reference comment works

### ISSUE THREAD

**Issue by YanChenBai** [vue-vine/vue-vine#135]
![image](https://github.com/user-attachments/assets/ddc1e527-db21-467f-a415-48d0ce33d124)

我在tsconfig.json中添加以下内容智能提示无效
```json
{
  "compilerOptions": {
    "types": ["vue-vine/macros"]
  }
}
```

但我在env.d.ts中添加了以下内容就正常了
```typescript
/// <reference types="vue-vine/macros" />
```

**Comment by ShenQingchuan** [comment]
请问一下您的项目方便开源仓库地址供我们复现问题么？如果不方便的话，想请问一下您项目的一些信息

- ts 的版本
- 当前 vue-vine 包的版本
- tsconfig.json 的内容

大概率怀疑是您的 moduleResolution 为 NodeNext 而非 bundler

**Comment by YanChenBai** [comment]
https://github.com/YanChenBai/test-vine

**Comment by alexzhang1030** [comment]
Hi, the reason is that you extended `tsconfig.app.json` on `tsconfig.vitest.json` but overridden its `compilerOptions.types`, but did not override its `include`, so the ts server got confused.

Add an `input` field on your `tsconfig.vitest.json` to solve this issue.

```diff
// tsconfig.vitest.json`
{
  "extends": "./tsconfig.app.json",
  "compilerOptions": {
    "composite": true,
    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.vitest.tsbuildinfo",

    "lib": [],
    "types": ["node", "jsdom"]
  },
+ "include": ["src/**/*.test.ts"],
  "exclude": []
}

```
