### ISSUE TITLE
Dynamic require of "sass" is not supported

### ISSUE THREAD

**Issue by gmono** [vue-vine/vue-vine#146]
An error occurred after adding the following code, and switching the dependency sass to a non-dev dependency was useless.
```ts
vineStyle.scoped(scss`
  .item.selected:not(.hovered) { }
`)

```

![image](https://github.com/user-attachments/assets/d5b39fcc-c5b0-4701-ab92-816700fd69c6)

**Comment by ShenQingchuan** [comment]
Maybe duplicated with #138 ?
Please share some information about your repo:
- package.json
- tsconfig.json
