### ISSUE TITLE
How to use with unocss

### ISSUE THREAD

**Issue by gmono** [vue-vine/vue-vine#148]
When used with unocss, I found that only the classes used in sfc are valid. The dynamic generation of unocss seems to be unable to detect the unocss classes written in vine.

**Comment by ShenQingchuan** [comment]
Hi～@gmono, thanks for giving Vue Vine a try！

It seems that only describe your current situation and problems in these a few words is somewhat not enough.

Would you mind sharing your repo or providing a minimal reproduction demo for us?

**Comment by gmono** [comment]
For example, if you use the two class names flex and flex-1 (generated by unocss) in a certain SFC, 
and use this unocss class in a vine component, 
these two classes can take effect. .

But if you use overflow-auto in the vine component at this time, this class will not take effect, which means that only the classes used in SFC will trigger unocss class name generation. 

After checking with the debugging tool, it was found that the class name used only in vine was indeed not generated.

**Comment by wzc520pyfm** [comment]
@gmono Maybe you need to specify unocss to extract the class name from the ts file.

https://unocss.dev/guide/extracting#extracting-from-build-tools-pipeline

**Comment by gmono** [comment]
yourecorrect
