### ISSUE TITLE
feat request: Can we import external css files in vine component? That's my idea

### ISSUE THREAD

**Issue by yuxi-ovo** [vue-vine/vue-vine#151]
## Components are much cleaner if external css can be imported
But the component will become asynchronous or is there a better solution? I'm just a little guy

<img width="597" alt="Snipaste_2024-09-16_02-28-44" src="https://github.com/user-attachments/assets/a65b41a0-ab3d-4662-b30f-59b48730573a">

**Comment by yuxi-ovo** [comment]
I get an error when I run the code like this
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/db6d32ee-47ec-4643-81d1-ccb0297aa167">

**Comment by ShenQingchuan** [comment]
This is a cool feature and was in my mind from the beginning of this project but I didn't put this in v0.1.0.

I'll add this to [Vue Vine TodoList](https://github.com/vue-vine/vue-vine/issues/75), thanks for your suggestion and also welcome any contribution from you!

**Comment by ShenQingchuan** [comment]
Close by #155
