### ISSUE TITLE
`create-vue-vine` is broken in Windows

### ISSUE THREAD

**Issue by 9romise** [vue-vine/vue-vine#158]
![image](https://github.com/user-attachments/assets/7ca14086-a8ba-439e-a95f-ed8b4225c605)

![image](https://github.com/user-attachments/assets/d812c396-aebc-4c0b-8439-f83550659814)

**Comment by ShenQingchuan** [comment]
@9romise 

Please install `v0.0.2` version of `create-vue-vine` and retry 💖
