### ISSUE TITLE
some packages (v0.1.29) are published incorrectly in `npm`

### ISSUE THREAD

**Issue by 9romise** [vue-vine/vue-vine#160]
- [`@vue-vine/eslint-parser`](https://www.npmjs.com/package/@vue-vine/eslint-parser?activeTab=code)

`index.js` and `index.mjs` are missing

![image](https://github.com/user-attachments/assets/7e9058ce-92cc-4de1-b60b-e59fd371be08)

- [`@vue-vine/compiler`](https://www.npmjs.com/package/@vue-vine/compiler?activeTab=code)

`index.js` is missing

![image](https://github.com/user-attachments/assets/8b64a3e4-eee9-44e8-90d6-5c45195beedc)

**Comment by ShenQingchuan** [comment]
Sorry for that unacceptable mistake, we'll immediately publish a fix version in v0.1.30

**Comment by ShenQingchuan** [comment]
The v0.1.29 `@vue-vine/eslint-parser` has been marked as deprecated

<img width="1244" alt="image" src="https://github.com/user-attachments/assets/16c7b7fc-c870-4448-ae65-0b7b54ec17f2">

Please use `0.1.30` and we recommend you to try `@vue-vine/eslint-config` instead use custom eslint parser manually. 

Anyway, glad to see you're interested in this project and thanks a lot for your report !! 💖
