### ISSUE TITLE
[feature request] starter CLI

### ISSUE THREAD

**Issue by vaakian** [vue-vine/vue-vine#17]
I was looking for a command like this to make a quick start:
```shell
pnpm create vue-vine # or another name
```
It will be sweet if there is one!

and I think `create-vue-vine`  should be register on `npmjs.com` right now, just in case there's a need in the future and potential rush registration by others.

**Comment by baiwusanyu-c** [comment]
Vue-Vine is not stable, I believe the author will consider doing so in the future

**Comment by ShenQingchuan** [comment]
> I was looking for a command like this to make a quick start:
> 
> ```shell
> pnpm create vue-vine # or another name
> ```
> 
> It will be sweet if there is one!
> 
> and I think `create-vue-vine` should be register on `npmjs.com` right now, just in case there's a need in the future and potential rush registration by others.

Thanks for your kindly suggestion!

Vine is under development, it's only a MVP version for now.
We have a lot of things to supplement before we're ready to launch v0.1 (which will be the first usable version of Vine)

But taking that registration will be done in these days, I'll catch up with that. Thanks!

**Comment by ShenQingchuan** [comment]
The `create-vue-vine` package has already been registered today.

I'll close this issue for now. After we launch the first release, you'll be able to use that as you expected.
