### ISSUE TITLE
Typo in specs page in docs

### ISSUE THREAD

**Issue by ElijahSink** [vue-vine/vue-vine#19]
https://vue-vine.netlify.app/design/spec.html#file-extension
here it says:
> Vine uses `.vite.ts` as the file extension, so you know that you're actually writing TypeScript, any valid grammar in TypeScript is also valid for Vine.

I think this is supposed to say `.vine.ts`.

**Comment by baiwusanyu-c** [comment]
You are right, thanks for pointing out this worng 👍
