### ISSUE TITLE
run `pnpm run docs:dev` and missing `vitepress` dependency?

### ISSUE THREAD

**Issue by watonyweng** [vue-vine/vue-vine#2]
I think we may need to run the following command.

```sh
pnpm add vitepress -d -w
```

**Comment by ShenQingchuan** [comment]
> I think we may need to run the following command.
> 
> 
> 
> ```sh
> 
> pnpm add vitepress -d -w
> 
> ```

Sorry for that😂

I used my local global installed vitepress to create docs project.

I'll fix it later.

**Comment by ShenQingchuan** [comment]
Fixed in [63747d7](https://github.com/vue-vine/vue-vine/commit/63747d730c88f87baf6b957e603b13eac629e3b6)
