### ISSUE TITLE
[bug]: setup doesn't return props correctly

### ISSUE THREAD

**Issue by baiwusanyu-c** [vue-vine/vue-vine#36]
# Bug reproduce sample
![348dc393887ca652f7d376d056659ac](https://github.com/vue-vine/vue-vine/assets/32354856/532bd8d8-618f-47e1-bae7-c0ee85ac85bb)

# Compile Result
![image](https://github.com/vue-vine/vue-vine/assets/32354856/b282746c-883f-4eae-98b7-25ddbbb410b2)

**Comment by baiwusanyu-c** [comment]
![image](https://github.com/vue-vine/vue-vine/assets/32354856/53d785d7-d052-41d4-b0d4-a1e7ef45825f)

**Comment by baiwusanyu-c** [comment]
![image](https://github.com/vue-vine/vue-vine/assets/32354856/4406e0bd-7752-4348-be41-e4c17e9897e1)

**Comment by baiwusanyu-c** [comment]
The rendering function still does not render content

**Comment by ShenQingchuan** [comment]
closed by a13feb0
