### ISSUE TITLE
[bug]: Some hot update codes should add dev judgment

### ISSUE THREAD

**Issue by baiwusanyu-c** [vue-vine/vue-vine#50]
https://github.com/vue-vine/vue-vine/blob/707cd4674ae536d639be9d482e25765708178f12/packages/compiler/src/transform.ts#L351

**Comment by baiwusanyu-c** [comment]
https://github.com/vue-vine/vue-vine/blob/707cd4674ae536d639be9d482e25765708178f12/packages/compiler/src/transform.ts#L342

**Comment by ShenQingchuan** [comment]
Close by bea23cf68
