### ISSUE TITLE
Support component TS type resolving in Volar context

### ISSUE THREAD

**Issue by ShenQingchuan** [vue-vine/vue-vine#53]
## Purpose

**Make Vue Vine become usage compatible with Vue SFC**

i.e. user can import the components that export from `.vine.ts` in `.vue` file, and no type issues.

This issue may need Volar 2.0 TS Plugin's help. 

We need to implicitly convert the "Vine component function" type to a "Vue component" object's type, based on information like props, emits and so on ...

I'd be so appreciated if @johnsoncodehk could provide some information about it. Thanks ❤️ !

**Comment by ShenQingchuan** [comment]
Tracking https://github.com/volarjs/volar.js/issues/85

Waiting for stable API from Volar 2.0

**Comment by so1ve** [comment]
We should collect props and slots definition from Vine SFC and convert them into pure TS files

**Comment by ShenQingchuan** [comment]
> We should collect props and slots definition from Vine function component and convert them into pure TS files

Sounds good! So what is the actual form/struct/content in those pure TS files?

```ts
// _VINE_VLS.virtual.ts ??

interface _Comp1_Props_ {
  // ...
}

interface _Comp_Slots {
  // ...
}

interface _Comp_Emits {
  // ...
}
```

You mean something like this ??

**Comment by so1ve** [comment]
Yes! And then we can convert Vine SFC into such code:

```ts
export default defineComponent({
  props: {} as _Comp1_Props,
  slots: {} as _Comp1_Slots,
  emits: {} as _Comp1_Emits,
})
```

**Comment by ShenQingchuan** [comment]
So you mean I need to write a complete process of this generation by myself manually or just provide these enough data for Volar new API?🥹🥰😜

**Comment by so1ve** [comment]
Not sure if volar provides such function 🥹
