### ISSUE TITLE
Use tsup to build packages

### ISSUE THREAD

**Issue by so1ve** [vue-vine/vue-vine#57]
Blocked by #56 #49, I don't want to do such refactor before these PRs merged since it will cause many merge conflicts.

**Comment by so1ve** [comment]
I can start the work now since #49 has been merged!

**Comment by ShenQingchuan** [comment]
#56 is merged and we can start a basic release preparation process for Vue Vine!

For now, those scripts are just enough to work, but a good engineer construction for a repo is indeed important.

So we can put this task to a higher priority,
