### ISSUE TITLE
[Astro] vineProp is not defined

### ISSUE THREAD

**Issue by luiguild** [vue-vine/vue-vine#68]
Hello, I'm trying to use Vine in my Astro project. I want to use the `vineProp.withDefault` macro, but I'm facing the following error:

![image](https://github.com/vue-vine/vue-vine/assets/16566338/11aab612-a3fa-4909-a689-53739639c04e)
👆 This error message is from WebStorm when I try to reach the `vineProp`.

![image](https://github.com/vue-vine/vue-vine/assets/16566338/53037a84-2796-473e-bcef-1df928efdcad)
👆 When I try to reach the `withDefaults` method, WebStrom recognize it. LOL

(this prop is just an example, the `false` value as a initial value doesn't interferes with the result)

My `astro.config.mjs` (is the same file from vite)
```
import { defineConfig } from "astro/config";
import vue from "@astrojs/vue";
import alias from "./aliases";
import { VineVitePlugin } from "vue-vine/vite";

// https://astro.build/config
export default defineConfig({
  resolve: {
    alias
  },
  plugins: [
    VineVitePlugin() // 👈 the plugin
  ],
  integrations: [
    vue({
      appEntrypoint: "/src/pages/_vue"
    })
  ]
});
```

My `tsconfig.json`
```
{
  "extends": "astro/tsconfigs/strict",
  "files": ["./src/**/*", "*.astro", "*.vue"],
  "include": ["./src/**/*", "./tests/**/*", "*.astro", "*.vue"],
  "compilerOptions": {
    "types": ["vue-vine/macro"], //👈 the types
    "resolveJsonModule": true,
    "baseUrl": ".",
    "moduleResolution": "node",
    "jsx": "preserve"
  }
}
```

👇 The error message from terminal during Astro build
```
[Vue warn]: Unhandled error during execution of setup function
  at <MultiButton type="button" >
 error   vineProp is not defined
  File:
    D:\...\component.vue:15:20
  Code:
    > 15 | const buttonType = vineProp.withDefault(false, (value: string) => value.includes('a'));
         |                    ^
```

Did I miss something? 🤔

This approach is exactly what I was looking for, congrats. Thanks!

**Comment by ShenQingchuan** [comment]
Thank you so much for trying this project! I'm not sure if this is a good fit for your project, but I can see from the tsconfig file you gave that you don't seem to reference the type definition of the Vine macro.

Refer to docs: https://vue-vine.dev/introduction/quick-start.html#use-macro-types

```diff
{
  "extends": "astro/tsconfigs/strict",
  "files": ["./src/**/*", "*.astro", "*.vue"],
  "include": ["./src/**/*", "./tests/**/*", "*.astro", "*.vue"],
  "compilerOptions": {
    "types": ["vue-vine/macro"], //👈 the types
    "resolveJsonModule": true,
    "baseUrl": ".",
    "moduleResolution": "node",
    "jsx": "preserve"
+   "types": ["vue-vine/macro"]
  }
}
```

**Comment by ShenQingchuan** [comment]
First of all, thank you very much for your willingness to use Vue Vine in your project. At present, it is a great pity that in the early stage of the project, I mainly focused on the integration of IDE functions on VSCode, and WebStorm may not be particularly well supported.

But at this point it seems that your problem is not IDE related, because you seem to be using vine macros in `.vue` files, which is not the intended use, and Vine macros only work in `.vine.ts` files.

**Comment by ShenQingchuan** [comment]
If you don't mind, could you share your code repository with me? I'd like to see if I can help you out.

**Comment by ShenQingchuan** [comment]
If we can't collect enough information here to solve this issue, we're going to close it temporarily.

Thanks for your exploring！
