### ISSUE TITLE
[Bug] `vineEmits` compiled incorrect

### ISSUE THREAD

**Issue by rumanHuq** [vue-vine/vue-vine#89]
<img width="897" alt="image" src="https://github.com/vue-vine/vue-vine/assets/13895272/6ba3a6c8-9d9b-4521-8e60-2e91ec4b5509">

```
function SubComponent() {
  const num = vineProp<number>()
  const tapEmit = vineEmits<{ tap: [number] }>()
  console.log({ tapEmit })
  return vine`
    <p>{{num}}</p>
    <button @click="()=>tapEmit('tap', num)">Click to log</button>
  `
}

export function App() {
  const num = 2
  return vine`<SubComponent :num="num" @tap="(n)=>console.log(n)"></SubComponent>`
}
```

**Comment by rumanHuq** [comment]
I meant `vineEmits` returns undefined. In the above code `tapEmit` is not a function
![image](https://github.com/vue-vine/vue-vine/assets/13895272/51cbb469-0f3a-4e19-ad15-e16d95141e5f)

**Comment by alexzhang1030** [comment]
I confirmed it is a bug. I will try to fix it.

**Comment by ShenQingchuan** [comment]
@rumanHuq 

Should be fixed in v0.1.2

**Comment by rumanHuq** [comment]
@ShenQingchuan there is another problem regarding the lexical scope. The same code now produce 
<img width="463" alt="image" src="https://github.com/vue-vine/vue-vine/assets/13895272/21502ac2-8447-42c2-9b75-714fd06a28a7">

**Comment by ShenQingchuan** [comment]
> You guys are on fire 🔥 !

Try version v0.1.3 and it should be fixed 😰 Sorry for our carelessness
