### ISSUE TITLE
create-vine 的时候，使用vineScope没有找到styleDefine，请问是因为啥？

### ISSUE THREAD

**Issue by zhangshuaiqiang11** [vue-vine/vue-vine#95]
Internal server error: Cannot read properties of undefined (reading 'styleDefine')
<img width="909" alt="image" src="https://github.com/vue-vine/vue-vine/assets/96008207/1c364ecb-d915-4b80-87fa-9f0207792a51">
<img width="417" alt="image" src="https://github.com/vue-vine/vue-vine/assets/96008207/661b28c5-9471-4244-9261-77d018955b14">

**Comment by zhangshuaiqiang11** [comment]
<img width="1172" alt="image" src="https://github.com/vue-vine/vue-vine/assets/96008207/8dba8eec-7013-41e4-948c-9071f667f18d">
找到原因，在compilerCtx.fileCtx.get(fullFileId)中，full显示的并非完整路径，而在compilerCtx.fileCtx中它的key为完整路径，所以导致取值为undefined，即后面我写入的固定的完整路径

**Comment by zhangshuaiqiang11** [comment]
<img width="1046" alt="image" src="https://github.com/vue-vine/vue-vine/assets/96008207/29047a23-7591-4da5-9f04-7a78b57ddeef">

**Comment by so1ve** [comment]
感谢您的问题报告与研究！有兴趣提一个PR来修复吗？

**Comment by alexzhang1030** [comment]
<img width="1248" alt="image" src="https://github.com/vue-vine/vue-vine/assets/49969959/d1328f5d-f33b-430f-b69f-0186667d55e2">

Hi, 未复现这个问题，可以提供一个最小复现吗🙏

**Comment by zhangshuaiqiang11** [comment]
不好意思，刚看到，不确定是我哪个环节出问题了，我昨天用mac和win安装新项目时，是又好了的，等我晚上回去，用那个出错的项目再看看

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月04日 09:51 |
| 收件人 | vue-vine/vue-vine ***@***.***> |
| 抄送人 | kyen_zhang ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [vue-vine/vue-vine] create-vine 的时候，使用vineScope没有找到styleDefine，请问是因为啥？ (Issue #95) |

image.png (view on web)

Hi, 未复现这个问题，可以提供一个最小复现吗🙏

**Comment by zhangshuaiqiang11** [comment]
目前安装没有遇到，先close
