### ISSUE TITLE
[eslint-parser]: Cannot find module 'lodash/*'

### ISSUE THREAD

**Issue by libondev** [vue-vine/vue-vine#99]
## Question description
I have noticed that when using ESLint and vue-vine, I encounter many error problems. After checking PlayGround, I discovered the ESLint Parser package. However, after installation, my ESLint VSCode plugin will not work due to the inability to find the module in this package.

我注意到在使用接入 eslint 并使用 vue-vine 的时候会遇到很多错误的问题，在查看 playground 以后我发现了 eslint-parser 这个包，但是安装以后我的 eslint vscode 插件会因为这个包无法找到模块而导致整个 eslint 的插件无法工作

<img width="1287" alt="image" src="https://github.com/vue-vine/vue-vine/assets/47918504/2307ade8-e6e1-467b-9851-bd404c49c18b">

After checking the packaging configuration, I found that the sub methods under lodash were not properly packaged. I think this is incorrect for an independent plugin because the plugin context of eslint is not always consistent with the main project

在查看打包配置以后我发现 lodash 下面的子方法没有被正确打包进去，我觉得这对一个独立的插件来讲是不正确的，因为 eslint 的插件上下文并不总是和主项目一致

<img width="935" alt="image" src="https://github.com/vue-vine/vue-vine/assets/47918504/0fd66cef-f6aa-4d9e-a784-64b546bd0b0d">

If my idea is correct and the problem does exist, then I would be happy to propose a PR to fix it. :)

如果我的想法是对的，并且这个问题确实存在，那么我很乐意提出一个 pr 来修复这个问题. :)

## How to reproduce
example: 
https://github.com/libondev/test-vue-vine/blob/main/eslint.config.js

**Comment by libondev** [comment]
I have observed that a lot of packages have been externalized, and I am not sure if there may be any issues in other scenarios, but after making this modification, it can work normally. :)

我观察到有非常多的包都被 external 了，我不确定在其他场景下会不会有问题, 但是我做出这项修改以后它就能正常工作了. :)

https://github.com/libondev/vue-vine/commit/907cec61dca0afa45d42ed69135773edc1935dcc

**Comment by ShenQingchuan** [comment]
Thanks for your research about this problem! It seems like that I indeed do something wrong with bundling lodash I'll processing it ASAP❤️！
